### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by mondalaci** [JeremiePat/jQuery-scrollPoint#5]
For some reason this plugin doesn't work for me unlike https://github.com/protonet/jquery.inview which works perfectly. Here's the code that I use:

```
    $('.hand-movements-minimized').scrollPoint();
    $(document).on('scrollPointEnter', '.hand-movements-minimized', function() {
        console.log('scroll point entered');
    });

    $('.hand-movements-minimized').bind('inview', function() {
        console.log('inview entered');
    });
```

`inview entered` appears when scrolling over the right element but `scroll point entered` never appears.

**Comment by tzi** [comment]
Hi @mondalaci!

`jQuery-scrollPoint` tracks scrolls, not the elements.
So you can do whatever you want with it, but the default behaviour is to throw an event when the scroll reaches the element and it starts to disappear, not when the element is viewed.

To track when an element is viewed on the screen, you should simply shift the `up` event from one height of the screen. You can use the following code:

```js
	$('.hand-movements-minimized').scrollPoint({
		offsetUp: $(window).height()
	});
	$(document).on('scrollPointEnter', '.hand-movements-minimized', function() {
		console.log('scroll point entered');
	});
```

I hope this helps!

Cheers,
Thomas.

**Comment by mondalaci** [comment]
Thanks for the clarification, @tzi, makes sense!
