### ISSUE TITLE
Registering on bower

### ISSUE THREAD

**Issue by tzi** [JeremiePat/jQuery-scrollPoint#6]
Hi!

Any plan to register `jQuery-scrollPoint` on `bower`?
Are you for or against?

Cheers,
Thomas.

**Comment by JeremiePat** [comment]
That could be done, I'm not against. Actually you can already use it with bower even if it's not registered (yeah, I know it's not as easy, but still possible)

**Comment by JeremiePat** [comment]
So I made some version tagging. I'll add a bower.json file very quickly.

**Comment by tzi** [comment]
Thanks @JeremiePat!

If you want help to maintain this library, do not hesitate to ask me.
I'm starting to know it well ;)

Cheers,
Thomas.

**Comment by JeremiePat** [comment]
Ok, done.

Just run: `bower install jquery-scrollpoint` and you're done :)

@tzi Yes why not ;) And I know that I still have to review your last pull request
