### ISSUE TITLE
Project in lower case

### ISSUE THREAD

**Issue by tzi** [JeremiePat/jquery-scrollpoint#7]
Hi @JeremiePat!

It seems that most of the jQuery plugins use lower case letters.
What do you think about changing the project name and the main file?

Project: `jquery-scroll-point` or `jquery-scrollpoint`
Main file: `jquery.scroll-point.js` or `jquery.scrollpoint.js`

Apparently, the hyphens are rarely used as separator in jQuery plugin names, but they improve readibility.

Cheers,
Thomas.

**Comment by JeremiePat** [comment]
I'm 100% okay for renaming :)
I suggest that we do not use hyphen as they make things hard in command line

**Comment by JeremiePat** [comment]
Okay, I lowered case the project, I'll handle the file name in the next days

**Comment by JeremiePat** [comment]
Okay, done :)
