### ISSUE TITLE
npm and/or bower support

### ISSUE THREAD

**Issue by tzi** [JeremiePat/jquery-scrollpoint#8]
Hi @JeremiePat!

What do you think of adding npm support?

I think npm could be great, it could really simplify the usage of this plugin.
I not a big fan of bower, since those who have bower have npm.

Cheers,
Thomas.

**Comment by JeremiePat** [comment]
Sounds good to me.

Bower remain a good idea as well as npm as some folks use it and it's not a burden to support it (but definitely, npm is more interesting).

**Comment by tzi** [comment]
Great!

I'll handle it so ;)

**Comment by tzi** [comment]
The package is created on npm: https://www.npmjs.com/package/jquery-scrollpoint

If you have a npm user account, tell me your username and I will grant you access ;)

Cheers,
Thomas.

**Comment by JeremiePat** [comment]
I have now ;)

> https://www.npmjs.com/~jeremiepat

**Comment by tzi** [comment]
Done!
